### ISSUE TITLE
Secure Pin Functionality

### ISSUE THREAD

**Issue by storkandstars** [SimplioOfficial/simplio-app#109]
# Overview

Add a functionality for prepared screens for inserting pin. Take use of secure token that is provided by `Account`. Setting up a security pin code should be always asked on loading application and last account. If an account is loaded and his security level is to low, we will be redirected to a set up pin screen. Seed cannot be generated if a user does not have a pin that encrypts a security token.

## Requirements

- Security levels
- Security level must reach at least pin before entering the app
- After account is loaded the pin modal will appear.

## Subtasks

- [ ] Prepare user flow for setting up a pin
- [ ] Prepare a form form of security
- [ ] Prepare security token and its encryption functionality
- [ ] Prepare security levels
- [ ] Prepare Pin screen after account is loaded
- [ ] Prepare Pin screen/modal for opening specific app's functionality
