### ISSUE TITLE
Setup environment

### ISSUE THREAD

**Issue by storkandstars** [SimplioOfficial/simplio-app#11]
## Overview

Prepare an environment for delivering and deploying flutter app

### Outcome

Environment with automatic continuous testing and deployment following out [workflow](https://github.com/SimplioOfficial/documentation/blob/master/docs/company/version-control.md)

### Requirements

- testing in CI/CD
- automatic builds
- deployment to test on merge to master
- deployment to prod on tagging version in master

### Task list
- [x] Build CI/CD 
- [x] #15
- [x] #16
- [x] AppStore deployment (dev)
- [x] AppStore deployment (production)
- [x] PlayStore deployment (dev)
- [x] PlayStore deployment (production)
- [x] Automatic version increase

**Comment by jvrastil** [comment]
https://github.com/SimplioOfficial/simplio-app/pull/28

**Comment by jvrastil** [comment]
@MariooW my part is finished and the branch is going to be merged into feature branch
