### ISSUE TITLE
Create UTXO wallet

### ISSUE THREAD

**Issue by daxicek** [SimplioOfficial/simplio-app#116]
# Overview

Create UTXO wallet from stored mnemonic phrase. Improve logic for wallet creation so we can create a wallet for every network.

## Requirements

- Go to inventory screen
- Search utxo asset
- Create a asset based on network

## Dev notes

- Asset can have multiple wallets of different network and different
- Games belong to many wallets

## Subtasks

- [x] Analyse system assets api and update `crypto_asset` package
- [x] Create a mnemonic for a account wallet
- [x] Encrypt created mnemonic with pin
- [x] Update data models for account and wallet
- [x] Create a provider and repository for account and wallets (Think of games as well)
- [x] Load a account wallet when needed
- [x] Enable asset wallets
- [x] Search available asset wallets
