### ISSUE TITLE
Implement WalletConnect v1

### ISSUE THREAD

**Issue by storkandstars** [SimplioOfficial/simplio-app#175]
# Overview

Implement wallet connect V1 with an external flow. It means we will get the wc uri from a qr scanner.

# Subtasks

- [x] Analyse wallet connect v1 implementation 
- [x] #176
- [x] Implement wallet connect library
- [ ] #175 
- [x] SimplioOfficial/sio_core_light#6
- [x]  SimplioOfficial/sio_core_light#11
- [x]  SimplioOfficial/sio_core_light#13

## Requirements
- simplio app must handle multiple wc connections
- restore connection when application is closed
- keep connection alive when app is minimised
- show active connection relative to account wallet
- show information about connected network (chainId)
- connection should be closed if the same wallet is already connected (if we connect to the same app, both from mobile and desktop)
- disconnect on requesting unsupported networks

## How to test
- Open from the QR scanner scan a DAPP (ex: https://example.walletconnect.org/)
- Check if connection is made.
- Try various methods and see if the result is correct. (eth_message (standart) is not working as is normal)
- Open another DAPP (ex: https://pancakeswap.finance/)
- Check if the connection is made.
- Try to make a swap in each direction (bnb <-> cake). (Must have some bnb in the testing wallet)
