### ISSUE TITLE
Asset send form

### ISSUE THREAD

**Issue by storkandstars** [SimplioOfficial/simplio-app#476]
# Overview

Send assets to another wallet. This tasks continues on previous application refactoring after mvp.

## Subtasks

- [ ] Select source asset
- [ ] Enter amount
- [ ] Get max amount
- [ ] Insert amount in crypto and fiat
- [ ] Paste or scan address
- [ ] Validate form
