### ISSUE TITLE
Abstract data layer

### ISSUE THREAD

**Issue by storkandstars** [SimplioOfficial/simplio-app#485]
# Overview

Create a abstraction for repositories and optimise object parsing

## Subtasks

- [x] Create database entities
- [x] Add Mappers for database entities
- [x] Introduce database interfaces
- [x] Introduce repository interfaces
