### ISSUE TITLE
Fetching wallet balance

### ISSUE THREAD

**Issue by storkandstars** [SimplioOfficial/simplio-app#486]
# Overview

Refactor fetching wallet balance on inventory screen and remove inventory repository as it does not belongs to the wallet domain.

## Subtasks

- [ ] Removing mvp placeholders
- [ ] Adding fiat balance to account asset and network wallet
- [ ] Updating balace service
- [ ] Updating wallet repository with balance updater
- [ ] Updating VVM
